version: '3'

services:
  bdd:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: enieni
      MYSQL_DATABASE: serieApp
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  db-data: