name: Integration continue pour Symfony 6
on:
  push:
    branches:
      - master
jobs:
  symfony:
    name: Symfony 6
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: enieni
        ports:
          - 3306:3306
    strategy:
      fail-fast: true
      matrix:
        php-version: ['8.0', '8.1'']
    steps:
      - name: GitHub checkout
        uses: actions/checkout@v3
      - name: PHP, extensions, composer
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php-versions }}
            extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring
        env:
            update: true
      - name: PHP version
        run: php -v
